server:
  port: 9000

cloud:
  eureka-host: localhost

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:h2:mem:auth-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${cloud.eurika-host}:8761/eureka
