server:
  port: 8090

cloud:
  db-host: localhost
  eureka-host: localhost
  currency-url: http://localhost:8080


spring:
  application:
    name: exchange-processing-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none


  datasource:
    url: jdbc:postgresql://${cloud.db-host}:5432/processing
    username: postgres
    password: docker
    driverClassName: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db
    url: jdbc:postgresql://${cloud.db-host}:5432/processing
    user: postgres
    password: docker

service:
  currency:
    url: ${cloud.currency-url}

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka