server:
  port: 8090

spring:
  application:
    name: exchange-processing-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/processing
    username: postgres
    password: docker

  flyway:
    enabled: true
    locations: classpath:db
    url: jdbc:postgresql://localhost:5432/processing
    user: postgres
    password: docker

service:
  currency:
    url: http://localhost:8085

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/